### ISSUE TITLE
Midl - credentialprovider.idl

### ISSUE THREAD

**Issue by hans-ahrens** [SteveSyfuhs/CredProvider.NET#1]
Hi,

When i try to run the code with my own intermediate dll file i cant get it to work. 
Is is possible to add a precompiled dll file to the repository ? So that i can test if the base code works on my machine.

Best Regards,
Hans

**Comment by SteveSyfuhs** [comment]
I should've mentioned this a while back, but I did add the DLL to the midl folder for this.
