### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by subu1979** [SteveSyfuhs/CredProvider.NET#11]
Hi,

Cloned & Re-builed the code in VS-2017.

On a virtual box (Windows 10), i have installed the Credential Provider using Install.reg. When i restart / Sign-out the System, could not see the NEW Credential Provider.

**Comment by TaiPhamD** [comment]
I dont think if you have this problem but I noticed the "allow COM  interop" check box wasn't set for my "Release" build and that broke the credential provider for me. The Debug build has that box check by default so I also set it checked on release and fixed my problem.

**Comment by subu1979** [comment]
Thanks
