### ISSUE TITLE
[Hyper-V] Can forwarded USB drives be accessed from the login page?

### ISSUE THREAD

**Issue by forderud** [SteveSyfuhs/CredProvider.NET#18]
I'm working on a custom credential provider that relies on a additional information from a special USB stick. This seem to work well when testing on physical HW as well as when testing _after_ user login in a Hyper-V "Enhanced session" that forwards connected USB drives to network shares beneath `\\tsclient`.
![image](https://user-images.githubusercontent.com/2671400/160147890-22988429-c7c6-46fa-8d2f-bbe2ead49c08.png)
![image](https://user-images.githubusercontent.com/2671400/160149094-c47bf9a7-d4ad-47d8-81f4-ef1b5cad51d5.png)

However, the credential provider doesn't seem to be able to access these forwarded USB drives from the Widows login page, meaning _before_ the user logs in. I'm wondering if this is a fundamental problem with Hyper-V, or if it's possible to somehow work around this limitation so that the credential provider more easily can be tested in a VM?

**Comment by SteveSyfuhs** [comment]
I don't have cycles to deal with this project anymore and I can't offer any help. This is entirely a behavior of the Hyper-V browser. Also, I am archiving this project. Please fork it for your own uses.
