### ISSUE TITLE
Open WinForm from CredProvider

### ISSUE THREAD

**Issue by tarakeshp** [SteveSyfuhs/CredProvider.NET#2]
Hi Steve,
Glad to meet you. I have been searching for Credential Provider ported in .Net. Thanks for that. However I am very new to these concepts. I have a requirement where a WPF or WinForm should popup. I work for a company called iCrypto. We Identity Verification and Attestation services company.
1. After primary auth is success, I would pull my custom cred provider with a winform containing an box to enter OTP from our iCrypto OTP
2. if user is not registered, using the same form user have to enroll by entering certain user details
3. the webapi details are preconfigured into registry  during msi installation.
4. I know window enumerates the dlls but help me in understanding how can I intiate the window form and if auth success is with OTP whatever, how can I return SUCCESS/OK event.
5. I could not able to understand cpp.
6. Also Could you breifly explain me what exactly happens when ICredentialsProvider is implemented and deployed. what is first method that executes on the dll.

**Comment by tarakeshp** [comment]
First I am trying this for Win 10 and then go to Win 8.1 and then to Win 7.

**Comment by SteveSyfuhs** [comment]
There are a number of useful docs you can take a look at that go through some of the specifics you ask:

 * https://docs.microsoft.com/en-us/windows/desktop/SecAuthN/credential-providers-in-windows
 * https://docs.microsoft.com/en-us/windows/desktop/SecAuthN/winlogon-and-credential-providers

Specifically the technical reference doc in the second link as that will provide you all the details of how the interfaces works.

I recommend trying it out in a VM to see how it all works. That's going to give you more information than I can write here. Also, take a look at this link for all the comments: https://syfuhs.net/2017/10/15/creating-custom-windows-credential-providers-in-net/
