### ISSUE TITLE
How do I support the CPUS_UNLOCK_WORKSTATION scenario?

### ISSUE THREAD

**Issue by nadcraker** [SteveSyfuhs/CredProvider.NET#4]
I am using your code and working on a Windows 10 Cred Provider, and I am having trouble with the CPUS_UNLOCK_WORKSTATION scenario. My CP simply serializes a Username and Password and logs the user in. This works in the CPUS_LOGON scenario, but I get a bad username and password in the CPUS_UNLOCK_WORKSTATION scenario.

According to MS docs (https://docs.microsoft.com/en-us/windows/desktop/api/credentialprovider/ne-credentialprovider-credential_provider_usage_scenario), "Credential providers that implement this scenario should be prepared to serialize credentials to the local authority for authentication. These credential providers also need to enumerate the currently logged-in user as the default tile."

How exactly do I do that? I think that the CredentialProviderBase:SetUserArray is the place to do it, but I don't know how.

Any insight you can give would be appreciated. Thank you.

I also posted this issue in https://github.com/phaetto/windows-credentials-provider because truthfully I am using code from both repos.

**Comment by SteveSyfuhs** [comment]
If all you're doing is collecting username and password you should just wrap the builtin CP and intercept right before it's serialized. That way you don't have to touch any of the code that sends it to LSA.


________________________________

**Comment by SteveSyfuhs** [comment]
I guarantee wrapping it is going to be much safer than building out your own in the long run. 🙂

The samples do show how to wrap it. Should be simple enough though. The other repo might have a more complete example too.


________________________________

**Comment by nadcraker** [comment]
I have so far successfully translated this sample https://github.com/pauldotknopf/WindowsSDK7-Samples/tree/master/security/credentialproviders/samplewrapexistingcredentialprovider to your C# code, but I am kind of confused on how I would wrap the `ICredentialProviderCredential` object.

In the C++ example, there is an initialize method that takes in a 'ICredentialProviderCredential', and then they assign it to their local object like so: `_pWrappedCredential = pWrappedCredential`.

I don't see an initialize method in your `CredentialProviderCredential.cs` class, or even in the 'ICredentialProviderCredential' interface here https://docs.microsoft.com/en-us/windows/desktop/api/credentialprovider/nn-credentialprovider-icredentialprovidercredential.

How can I get a reference to the password provider's `ICredentialProviderCredential` and call it from my wrapped credential?

**Comment by SteveSyfuhs** [comment]
It looks like the wrapped credential is presented during the provider call GetCredentialCount.

https://github.com/pauldotknopf/WindowsSDK7-Samples/blob/master/security/credentialproviders/samplewrapexistingcredentialprovider/CSampleProvider.cpp#L278
