### ISSUE TITLE
Trigger Custom  Provider pragmatically (i.e. Rest Api) 

### ISSUE THREAD

**Issue by Peymanmi** [SteveSyfuhs/CredProvider.NET#5]
Hi,

Thanks for this sample, It's just a question no bug report.

Is it possible to trigger the authentication by Api? 

I saw your sample and shows the Prompt, Actually I want to  call the custom provider directly by Api, no user click or any action from user.

Thanks in advance.

**Comment by SteveSyfuhs** [comment]
If you just want to prompt: https://github.com/SteveSyfuhs/CredProvider.NET/blob/master/CredProvider.NET.Tester/CredUI.cs#L31

If you want to limit what providers are shown you need to build a filter: https://docs.microsoft.com/en-us/windows/win32/api/credentialprovider/nf-credentialprovider-icredentialproviderfilter-filter

________________________________

**Comment by Peymanmi** [comment]
Thanks for your quick answer. 
I don't want to prompt at all. Just I want to do all pragmatically. By ode choose credential and authenticate it

**Comment by SteveSyfuhs** [comment]
There's no way to get a raw cred without prompting. You can ask for a derived cred like a kerberos ticket or NTLM token using SSPI.

________________________________

**Comment by Peymanmi** [comment]
Thanks again for response. Do you have any idea how can I configure this code which working with SmartCard Authentication?

**Comment by SteveSyfuhs** [comment]
I would recommend starting here: https://docs.microsoft.com/en-us/windows/win32/secauthn/sspi

**Comment by Peymanmi** [comment]
Thanks @SteveSyfuhs, I'll close this ticket.
