### ISSUE TITLE
How do I use the SetFieldBitmap method from ICredentialProviderCredentialEvents?

### ISSUE THREAD

**Issue by nadcraker** [SteveSyfuhs/CredProvider.NET#8]
I am successfully using the `GetBitmapValue` method in `ICredentialProviderCredential` to set my tile's logo.

```
Bitmap tileIcon;
tileIcon = Resources.blocked2;
phbmp = tileIcon?.GetHbitmap() ?? IntPtr.Zero;
```
But how do I change that bitmap later on when I call `SetFieldBitmap` method from `ICredentialProviderCredentialEvents`?
I don't know how to convert from `System.Drawing.Bitmap` to `_userHBITMAP`. 

This is what I have tried:
```
Bitmap newLogo = Resources.unblocked;
IntPtr phBmp = newLogo.GetHbitmap();
credentialProviderCredentialEvents.SetFieldBitmap(this, 2, ref phBmp);
```
This doesn't work because `SetFieldBitmap` wants a `_userHBITMAP` and not an `IntPtr`. 

I've never heard of a `_userHBITMAP` and can't find any documentation on how to use it.

**Comment by SteveSyfuhs** [comment]
That's tlbimp conversion causing problems. It doesn't understand HBITMAP is a typedef of HANDLE. This requires manually modifying the idl file. See here: https://github.com/SteveSyfuhs/CredProvider.NET/commit/340caafefdc76e17dbf4c2ea18bfdd38bdd5ca37#diff-f78edb28c8481eb3874fd33962980a1b6d21413531efce2c4c1d33a8dd9e44ecR151

For instructions on how to regenerate the DLL you can see here: https://syfuhs.net/2017/10/15/creating-custom-windows-credential-providers-in-net/

**Comment by nadcraker** [comment]
So I need to manually modify the idl file and then regenerate the DLL?

**Comment by SteveSyfuhs** [comment]
Well, took care of in the sense that I did a first pass of it to get the initial load working. Clearly I missed an HBITMAP or two. There's probably a few other things I missed too. I wasn't aiming for a perfect implementation. Alternatively you can create the interfaces yourself from scratch, but that would take some effort.

**Comment by nadcraker** [comment]
Ah, ok. That makes sense. I'll try and modify the idl and regen the DLL. Thanks a lot for your help
